In [20]:
import numpy as np

## Scalar and One-Dimensional Array

https://machinelearningmastery.com/broadcasting-with-numpy-arrays/

In [21]:
# python style
nums = [1,2,3]
nums + [4]

[1, 2, 3, 4]

In [22]:
a = np.array([1, 2, 3])
print(a)
b = 2
print(b)
c = a * b
print(c)

[1 2 3]
2
[2 4 6]


In [23]:
a // b

array([0, 1, 1])

In [24]:
a / b

array([0.5, 1. , 1.5])

In [25]:
A = array([[1, 2, 3], [1, 2, 3]])
print(A)
b = 2
print(b)
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


In [26]:
# 1D Array + 2D Array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)
b = array([7, 8, 9])
print(b)
C = A + b
print('C', C)

[[1 2 3]
 [4 5 6]]
[7 8 9]
C [[ 8 10 12]
 [11 13 15]]
